### PR TITLE
Add support for Google Analytics 4.

### PR DESCRIPTION
**Pull request by boazsender**
Removes support for Google Analytics 3.

#### I have verified this PR works with

-   [X] Online form submission
-   [X] Form preview

#### What else has been done to verify that this works as intended?
I created a test google analytics 4 property, added it to my enketo-express config.json, and confirmed that events are being recorded.

#### Why is this the best possible solution? Were any other approaches considered?
I copied the way former google analytics 3 implementation worked.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Google analytics 3 config will no longer work. Only a google analytics 4 `measurementId` config property will work.

#### Do we need any specific form for testing your changes? If so, please attach one.
Any form should work.

### CODE REVIEW

**Comment by lognaturel** [comment]
Can you also update https://github.com/enketo/enketo/blob/13616ecf253297465e90a78ae36691ac676e7343/packages/enketo-express/config/sample.env#L53, please?

Strictly speaking I think this would be a semver major change. Because Google Analytics 3 is not supported anymore so it's more like removing broken functionality and then adding something new, I think we can do semver minor, does that sound right?

**Comment by boazsender** [comment]
@lognaturel I've updated the sample env with my guess about how the env file works. I only tested with the config.json. Can you confirm it looks right, or advise me how to test with the env file locally?

Semver minor sounds right to me even though this is theoretically not backward compatible, since GA3 is deprecated, and is not working in folks' instances. Would have left GA3 in if it were operable.

**Comment by lognaturel** [comment]
The approach for converting config file entries to env var names is described at the top of the sample file. What you've done looks good.

You can try it by omitting the config file and setting the desired env variables.

**Review by lognaturel — DISMISSED** [review]

**Comment by lognaturel** [comment]
Could you please look at the failing test?

**Comment by boazsender** [comment]
Test updated. Wow, great to see the amazing test coverage in this project. I'll be sure to run them in the future prior to sending PRs.

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Yes! It has thorough linting as well so you'll also want to run `yarn lint` or `yarn lint --fix`.

**Pull request merged**
