### PR TITLE
Forward auth cookie when making max-size request to form server

### PR DESCRIPTION
**Pull request by FrankApiyo**
Closes: https://github.com/enketo/enketo/issues/994
Closes: https://github.com/onaio/onadata/issues/2568

#### I have verified this PR works with

-   [x] Online form submission
-   [x] Offline form submission
-   [x] Saving offline drafts
-   [x] Loading offline drafts
-   [x] Editing submissions
-   [x] Form preview
-   [ ] None of the above

#### What else has been done to verify that this works as intended?
Tested locally

#### Why is this the best possible solution? Were any other approaches considered?
Yes, I considered [allowing HEAD requests on this endpoint to be unauthenticated on onadata side
](https://github.com/onaio/onadata/pull/2565)
#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
No regression risks that I can think of

#### Do we need any specific form for testing your changes? If so, please attach one.
No

### CODE REVIEW

**Comment by FrankApiyo** [comment]
I noted while testing this locally that the HEAD request to the submission endpoint is sent without any authentication (set to `null`) and without any cookies. I believe this isn't the desired behaviour
```
{
  url: 'http://192.168.100.65:8000/enketo/9/submission',
  auth: null,
  headers: { cookie: undefined },
  method: 'head'
}
```

The fix presented here is to relay cookies sent from the browser to the ODK server

**Comment by lognaturel** [comment]
You have a form that requires cookie-based auth and it looks like cookies aren't forwarded when making the HEAD request to get max-size from Enketo backend to the form server, is that right?

Do you believe this to be a change in behavior in Enketo? Is there some change on your end that revealed this now?

**Comment by FrankApiyo** [comment]
This is right
> You have a form that requires cookie-based auth and it looks like cookies aren't forwarded when making the HEAD request to get max-size from Enketo backend to the form server, is that right?

No, this is not a change in behavior in enketo. It seems that the max-size endpoint has always worked like this (the request has always been made without credentials).

**Comment by lognaturel** [comment]
Great, thanks for the background. It looks like it was probably an accidental oversight but I do want to give it some thought and look at the code around this area more carefully since this is auth-related.

**Review by lognaturel — APPROVED** [review]
This excludes the direct XForm URL case and matches the behavior with basic/digest auth.

**Pull request merged**
